<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW9VAZX1\App_KernelDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW9VAZX1/App_KernelDebugContainer.php') {
    touch(__DIR__.'/ContainerW9VAZX1.legacy');

    return;
}

if (!\class_exists(App_KernelDebugContainer::class, false)) {
    \class_alias(\ContainerW9VAZX1\App_KernelDebugContainer::class, App_KernelDebugContainer::class, false);
}

return new \ContainerW9VAZX1\App_KernelDebugContainer([
    'container.build_hash' => 'W9VAZX1',
    'container.build_id' => 'abd853de',
    'container.build_time' => 1619422695,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW9VAZX1');
