<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE7lrexZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE7lrexZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE7lrexZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE7lrexZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE7lrexZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'E7lrexZ',
    'container.build_id' => '16718177',
    'container.build_time' => 1620035174,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE7lrexZ');
