<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app_assessment_index' => [[], ['_controller' => 'App\\Controller\\AssessmentController::index'], [], [['text', '/assessment']], [], []],
    'app_assessment_manual' => [[], ['_controller' => 'App\\Controller\\AssessmentController::manual'], [], [['text', '/assessment/manual']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\AssessmentController::index'], [], [['text', '/assessment']], [], []],
];
